openapi: 3.1.0
info:
  title: Order API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /orders:
    get:
      summary: Get all orders
      responses:
        '200':
          description: A list of orders